Integrated user's name in dashboard with email
BRAVO68WEB/url-minify pull request #154
Opened 2022-05-11 19:21 UTC by Anirban-1490

Fixes #146 

Added user's name and additionally email in the dashboard after login

Image - 

![Capture](https://user-images.githubusercontent.com/82874704/167929143-4d749b0e-c180-4719-81d4-75ffd18f9a8e.JPG)

2022-05-16 03:36 UTC, BRAVO68WEB commented
Can you make the "Brand Name" to URL Minify

2022-05-16 03:49 UTC, BRAVO68WEB approved these changes

2022-05-16 03:50 UTC, BRAVO68WEB requested changes

2022-05-16 03:50 UTC, BRAVO68WEB commented on frontend/helpers/user/userState.js
> +        name: username,
Why is this "username" as you have previously mentioned it as "name"

2022-05-17 17:57 UTC, Anirban-1490 commented
> @BRAVO68WEB Check it now, did all the changes you asked .
> 
> ![Capture](https://user-images.githubusercontent.com/82874704/168630705-ab1060ad-7afc-4c47-8c0e-1f63e9d71549.JPG)

@BRAVO68WEB ?

2022-05-17 18:09 UTC, BRAVO68WEB commented
Ok I will. Heck by tomorrow and merge

2022-05-18 07:08 UTC, BRAVO68WEB approved these changes

2022-05-18 07:09 UTC, merged